# Generated by Django 4.0.5 on 2022-06-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueblesList_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('imagen', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('website', models.URLField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Inmueble',
        ),
    ]
