# Generated by Django 4.0.5 on 2022-06-29 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmueblesList_App', '0004_rename_edificaciones_edificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacion',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='edificacion', to='inmueblesList_App.empresa'),
            preserve_default=False,
        ),
    ]
